### ISSUE TITLE
Practica1- Diagrama de clases 

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/practica-architect-KarlaV0#1]

**Comment by KarlaV0** [comment]
[FINGENIERIA DE SOFTWARE - PRACTICA1 DIAGRAMA DE CLASES.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-KarlaV0/files/7173490/FINGENIERIA.DE.SOFTWARE.-.PRACTICA1.DIAGRAMA.DE.CLASES.pdf)

**Comment by Yabin-2021** [comment]
Muy buen trabajo...
Puntaje **20 %**

**Comment by josealfredo79** [comment]
Bien hecho y revisado
